### ISSUE TITLE
Nav abstraction

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/CONTRIBUTING#1]
Hi Harry,

You have add the `tabs` object and created a `responsive-nav` on [jsfiddle](https://github.com/csswizardry/inuit.css/blob/master/objects/_nav.scss), but I wonder if you will add or make changes to the `nav` object from [inuit v5](https://github.com/csswizardry/inuit.css/blob/master/objects/_nav.scss)?

I think horizontal and vertical nav remain basic object that are very helpful.

**Comment by florianbouvot** [comment]
What do you think of three objects :
- an horizontal nav object
- a vertical nav object
- a responsive nav object : an abstraction for vertical to horizontal nav with one breakpoint

**Comment by csswizardry** [comment]
I’m thinking (because we have `bare-list`) we rename the `nav` abstraction to `inline-list`.

Then I think it’s probably best to rename them both to `list-bare` and `list-inline`.

The responsive aspect will be tricky; that might need to be another feature for another time :)

**Comment by csswizardry** [comment]
> Then I think it’s probably best to rename them both to list-bare and list-inline.

Actually, probably not, seeing as that would mean moving `ui-list`, `block-list`, etc. over to that paradigm.

**Comment by csswizardry** [comment]
Initial object in place: https://github.com/inuitcss/objects.inline-list

**Comment by florianbouvot** [comment]
Thanks Harry. I would prefer that the names begin with `list-` but I understand that you didn't want to rename every modules now ;)

**Comment by csswizardry** [comment]
Yeah, I’ll do that… best to do it now a) while there aren’t dozens of them and b) while these are all `0.x.x`.

**Comment by florianbouvot** [comment]
Well seen ;)

**Comment by florianbouvot** [comment]
It's weird to see all the modules change their names when used for months.
