### ISSUE TITLE
Will comments include examples of usage and links to interactive demos?

### ISSUE THREAD

**Issue by iDGS** [inuitcss/CONTRIBUTING#11]
I know it's still "early," roadmap-wise, but, just for the record, I miss the extensive descriptions of appropriate usage and links to live demos on jsfiddle that were among the riches of "old" InuitCSS.

E.g., compare the leading comments in the code for NEW media object: 

<code>https://github.com/inuitcss/objects.media/blob/master/_objects.media.scss</code>

<pre><code>/*------------------------------------*\
    #MEDIA
\*------------------------------------*/

/**
 * Place any image- and text-like content side-by-side, as per:
 * stubbornella.org/content/2010/06/25/the-media-object-saves-hundreds-of-lines-of-code
 */</code></pre>

vs OLD: 

<code>https://github.com/csswizardry/inuit.css/blob/master/objects/_media.scss</code>

(with apologies for using { below, b/c I couldn't figure out how to escape the <'s)

<pre><code>/*------------------------------------*\
    $MEDIA
\*------------------------------------*/
/**
 * Place any image- and text-like content side-by-side, as per:
 * stubbornella.org/content/2010/06/25/the-media-object-saves-hundreds-of-lines-of-code
 * E.g.:
 *
   {div class=media}
       {img src=http://placekitten.com/200/300 alt="" class=media__img}
       {p class=media__body}Lorem ipsum dolor sit amet, consectetur adipisicing elit,
       sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.{/p}
  {/div}
 *
 * Demo: jsfiddle.net/inuitcss/cf4Qs
 *
 */</code></pre>

Such details were a large part of the awesomeness of the previous edition, and very helpful for smart-ifying noobs and dilettantes such as myself.

I suspect it's something you're planning to include later, thus I just wanted to applaud and +1 the idea here.

**Comment by csshugs** [comment]
As long as we are waiting for an official documentation, stick with [this](http://csshugs.github.io/inuit-kitchen-sink/) ;-)

**Comment by florianbouvot** [comment]
@csshugs :+1: nice work, thank you.

**Comment by iDGS** [comment]
@csshugs  Wow! Thanks!

Here's some more thumbs-ups! :+1: :+1:  :-)

**Comment by graste** [comment]
Thanks.

**Comment by csshugs** [comment]
You're welcome.

**Comment by anselmh** [comment]
Hey, thanks for this report. We’re going to improve documentation a lot in future and therefore I’m going to close this issue now.
