### ISSUE TITLE
Push/Pull

### ISSUE THREAD

**Issue by csshugs** [inuitcss/CONTRIBUTING#12]
Do you plan to add push and pull modules as an extension for the layout-object, similar to inuitcss v5?
If not, there may be a new plugin waiting.

**Comment by csshugs** [comment]
Impatience is a virtue:

[inuit-push](https://github.com/csshugs/trumps.push)
[inuit-responsive-push](https://github.com/csshugs/trumps.push-responsive)

[inuit-pull](https://github.com/csshugs/trumps.pull)
[inuit-responsive-pull](https://github.com/csshugs/trumps.pull-responsive)

**Comment by nenadjelovac** [comment]
@csshugs thank you for your impatience! :)
