### ISSUE TITLE
Vertical rhythme applied on base tag

### ISSUE THREAD

**Issue by alienlebarge** [inuitcss/CONTRIBUTING#13]
I'm currently working on `_base.vertical-rythme.scss` to applied some vertical rhythm settings on base tags (`h1`, `h2`, ...,`p`, `ul`, ...).
[Here's the code](https://github.com/alienlebarge/alienlebarge.github.com/blob/d5fa86b704d0a56b0f44bb4dbf44b940ad93a0d2/stylesheets/_base.vertical-rythme.scss)

Perhaps it can be an addition to inuitcss

**Comment by csshugs** [comment]
@alienlebarge 
Thanks a lot for your suggestion and your example. Although it's a good idea and probably useful to many people, I'm afraid it's still too opinionated and [complex](https://github.com/inuitcss/CONTRIBUTING#simplicity-is-paramount) for inuitcss.

We'd still love to see such things being provided as some kind of inuitcss-plugin though. We want inuitcss to be as simple and granular as possible and instead let the users extend the framework with such modules as you suggested.

Still thank you very much for the effort!
