### ISSUE TITLE
Split modules, ie: object.settings & object.data

### ISSUE THREAD

**Issue by rdinigel** [inuitcss/CONTRIBUTING#14]
...Sorry if this is the wrong place for the issue...

Is it possible to split the object and its defaults like the previous version.

The reason for the ask:
When working in teams/open source, after installing via bower and moving via a GruntJS task the developer will need to change false to true on the required objects.

If this was split like `inuit-list-block/_object.list-block.scss` & `inuit-list-block/default.list-block.scss` then you can have a project SCSS file with all the defaults initialised and the imports stored within the repo instead of installing/moving the module and then changing the defaults each time you install or create new environments, if that makes sense? At least if it were split in two, or a config section to copy|paste from the readme you can then setup the way you need too.

Thoughts? :smiley:

**Comment by NigelGreenway** [comment]
Please close this as I am an idiot and have just realised what the `!default` argument does.

-- Sorry

**Comment by florianbouvot** [comment]
@NigelGreenway no access to @rdinigel account to directly close this issue ?

**Comment by NigelGreenway** [comment]
Oh, no I haven't.

I can try to get that sorted.
