### ISSUE TITLE
(RFC) object namespaces

### ISSUE THREAD

**Issue by NigelGreenway** [inuitcss/CONTRIBUTING#15]
Currently there are files named `_tools.responsive.scss`, `_objects.media.scss`, `_trumps.clearfix.scss` and so on...

I would like to propose extending the namespace when there are a collection of objects in a namespace.

For instance, `_tools.responsive.scss` works perfectly fine as it is a single tool however the `_tools.mixins.scss` seems like it could store multiple mixins as the framework grows.

I am proposing one file within a collection of functions with a namespace like so:

`_tools.mixin.opacity.scss`
`_tools.mixin.inuit-font-size.scss`
`_tools.helper.float.scss`
`_tools.helper.text-align.scss`

This will allow for the project to only use what is needed from the InuitCSS framework.

**Comment by csshugs** [comment]
Since this repository is now officially deprecated, I close this.
If this issue is still relevant, please open a new issue in the [new repository](https://github.com/inuitcss/inuitcss).

Thanks for your time and your effort.
