### ISSUE TITLE
How to help?

### ISSUE THREAD

**Issue by stereokai** [inuitcss/CONTRIBUTING#16]
@csswizardry Hey Harry, I really want to get involved in this project. I have been following it for a long time since I've discovered it. I have never been happy, not to say too impressed with any of the big or small CSS frameworks, and I truly believe in the Inuit way!

So, how can I help?

**Comment by anselmh** [comment]
Hi @stereokai, thanks for this. Feel free to solve any of the open issues (that are confirmably an issue with the codebase) and create a pull request we can review. That’s the best way to contribute.

**Comment by stereokai** [comment]
@anselmh Got it.
