### ISSUE TITLE
trumps.hide-responsive

### ISSUE THREAD

**Issue by mhauken** [inuitcss/CONTRIBUTING#17]
Hi, Harry!
Thanks for a great framework.

I've been using it on a lot of client-projects, and I've found that I often need to hide certain elements at different breakpoints. I've therefore modified your widths-responsive to suit this need.

If you are using inuitcss’ default breakpoints, you will be given classes like `lap-and-up-hide`, or `desk-hide`, etc.

https://github.com/mhauken/trumps.hide-responsive

**Comment by csshugs** [comment]
See also https://github.com/csshugs/trumps.hide

**Comment by csshugs** [comment]
@mhauken 
Thanks for the effort of providing a inuitcss-plugin 🎉 .

Although it's probably very useful for a lot of users, we won't implement such thing in the current version of inuitcss. We rather want to encourage inuitcss users to provide such modules as kind of plugins for the framework ([just as you did](https://github.com/mhauken/trumps.hide-responsive)). With that, we hope to keep the core framework useful to as many people as possible (you know, less is more 😉 ).

Still, thanks a lot for pointing this out though!
