### ISSUE TITLE
Flexbox grids

### ISSUE THREAD

**Issue by inlikealion** [inuitcss/CONTRIBUTING#20]
Hey all, I would love to see the grid system rewritten and expanded in **flexbox**. With tools like autoprefixer and old browser requirements slipping away (I mean fewer of us are having to support old browsers 'to look the same' as modern ones), moving to flexbox gives us a ton of less-hacky layout options.

One of the biggest pros this affords us is circumventing the “whitespace issue”. I've been reading up on flexbox and playing around a little bit, but am not at the point where I can rewrite this for my current project. Maybe after it launches I'll get some time to look into it, but I would love to gather community ideas or support someone else if they want to take the initiative. 

Have any of you worked on this? Would anyone want to take the charge (of course I'd love @csswizardry to weigh in here)?

**Comment by renatocarvalho** [comment]
@inlikealion Have a look on this.

The [fundament.grid](https://github.com/felics/fundament.grid) is a flexbox-first grid with inline-block fallback. It was inspired on [csswizardry-grids](https://github.com/csswizardry/csswizardry-grids).

**Comment by alienlebarge** [comment]
I'm currently building a [flexbox grid system](https://github.com/alienlebarge/inuit-flexbox) for inuitcss.
Let's build it together :wink:

**Comment by csshugs** [comment]
@inlikealion @renatocarvalho @alienlebarge 
Don't want to crash the party, but as I'm aware, flexbox is not intended to be used for overall page layout. That's what [CSS Grid Layout](https://medium.com/@patrickbrosset/css-grid-layout-6c9cba6e8a5a) is for.

Anyway, I created an [inuit plugin](https://github.com/csshugs/objects.flex-layout) myself, too. Just to be able to use something more convenient than the standard `inline-block` Grid and having the ability to have grid items with same heights.

But I don't think we should integrate something like this into the framework itself but rather wait for [acceptable browser support for CSS Grid Layout](http://caniuse.com/#feat=css-grid).

**Comment by inlikealion** [comment]
Thanks for the share @csshugs! Though, I only think people are saying flexbox is not for overall layout right now because overall site structure is too important to leave to the new layout engine. I.e. it's safer to progressively enhance micro layouts to flexbox with less-than-desirable fall-backs than your entire site to be laid out in a fall-back situation.

In other words, when CSS Grids get closer to being usable, it will probably have the same recommendation (use as enhancement on non-mission critical until support is closer to ~98%).

I _believe_ this to be the case, but may be wrong so feel free to push back. :)

**Comment by csshugs** [comment]
@inlikealion 
This is what I was referring to:
http://lists.w3.org/Archives/Public/www-style/2013May/0114.html

**Comment by csshugs** [comment]
Since this repository is now officially deprecated, I close this.
If this topic is still relevant to you, please open a new issue in the [new repository](https://github.com/inuitcss/inuitcss).

Thanks for your time and your effort.
