### ISSUE TITLE
Add base/forms module

### ISSUE THREAD

**Issue by corbpaul** [inuitcss/CONTRIBUTING#21]
Just an idea on a new module to be added to inuit.css

Some simple form elements such as these: 
https://github.com/corbpaul/inuit/blob/inuit-extended/base/_base.forms.scss

**Comment by drmonkeyninja** [comment]
:+1: 

Forms used to be part of Inuit but as far as I can see have since been removed which is a shame as it is something I used to use a lot.

**Comment by csshugs** [comment]
Since this repository is now officially deprecated, I close this.
I transferred it to the [new repo](https://github.com/inuitcss/inuitcss/issues/156) though, to keep the discussion going.
