### ISSUE TITLE
Rename "trumps" layer to "utilities"

### ISSUE THREAD

**Issue by csshugs** [inuitcss/CONTRIBUTING#24]
@aaronstezycki came up with this question [here](https://github.com/inuitcss/getting-started/issues/4#issuecomment-143732233). 
I think it's better to create a proper issue here for discussion.

**The idea is to remane the "trumps" layer to "utilities".**

What I like about "trumps" is that the naming hints at its function, i.e. to trump everything else because you definitely want to take it effect, whatever the class is doing. Since every declaration in this layer has to contain an `!important`, the correlation in naming is more obvious (to me) than it would be with "utilities".

On the other hand, naming this layer "utilities" would align it with other frameworks like SUIT CSS and Foundation (naming wise) and probably would clear any confusion to inuit newbies, don't familiar with the trumps layer.
An even more obvious pro for "utilities" is the soon coming [u-namespace](http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/). The `t-` namespace is reserved for "theme" so it seems like we have to go with the `u-` namespace for the **t**rumps layer. Confusing right? I think this is an important point to consider. When introducing these namespaces to the framework, renaming the layer to "utilities" would definitely prevent any confusion.

Any thoughts @nenadjelovac @florianbouvot ?

**Comment by nenadjelovac** [comment]
> What I like about "trumps" is that the naming hints at its function, i.e. to trump everything else because you definitely want to take it effect, whatever the class is doing. 

I really like this and I am personally comfortable with the name. But there is a lot of confusion for other people, and the second pro for "utilities" you (@csshugs) raised is something that makes me think we should probably rename it.

cc @csswizardry

**Comment by dennisfrank** [comment]
Yep. That makes a lot of sense. And I ran into some trouble myself explaining the u-namespace for the trumps level.

**Comment by florianbouvot** [comment]
I fully agree with @nenadjelovac

Beyond that, I think the main problem is the maintenance of the framework. There's much point to validate and implement (namespaces, placeholder/silent classes, documentation, ...). 
I do not blame @csswizardry (quite the opposite), but IMO I think he should oversee developments and accept your help...

Update : it isn't as important, but I think @csswizardry, has also changed `base` layer name to `elements`.

**Comment by nenadjelovac** [comment]
@florianbouvot 

> Update : it isn't as important, but I think @csswizardry, has also changed base layer name to elements.

Yup, I stumbled upon some examples from him somewhere.

**Comment by aaronstezycki** [comment]
Again, I think the above makes sense. (Renaming base to elements) I initially thought that base directory was a folder for *base* styles, and thus lead me to believe that the table styles should have been placed there, but I now know the reason for its placement within objects directory.

Again I think its just a learning curve and once people understand the structure, everything else falls into place.

**Comment by jacquesletesson** [comment]
Will make more sense to use the u- namespace indeed.

**Comment by csshugs** [comment]
Closing this, since we won't introduce such a huge change in the pre-alpha version. 

Also, this is already implemented in the [beta version](https://github.com/inuitcss/inuitcss/tree/develop/utilities).
