### ISSUE TITLE
About enable option

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/CONTRIBUTING#25]
From project to project I wonder about enable option (`$inuit-enable-...`). 
At first I thought it was a good things because it reduce CSS file size... But since I realize that it's not easy to know if an option is used or not (during development and following the launch). 

Is there a significant file size between "full framework" and "enable framework" after gzip ? 
What do you think about plugin like [gulp uncss](https://www.npmjs.com/package/gulp-uncss/) ?

cc @nenadjelovac @csshugs ?

**Comment by csshugs** [comment]
@florianbouvot 
I personaly am not a big fan of tools like uncss per se. It's a good tool to clean up at the end of the line, but only after I – a human being – have done all I can, to keep the file size low. I don't like to give away too much control to yet another tool in the line, which I have to rely on. But the file size isn't even the point here I think (although I think there is a significant difference between "full framework" and "enable framework"). I think it could be far more distracting not knowing which classes are really used in the markup and which are not when everything is enabled. In other words: Having so much unused CSS lying around in your codebase cannot be a good thing.

Beyond that, I think ["Off by default"](https://github.com/inuitcss/getting-started#off-by-default) is a core principle of inuitcss and makes it unique compared to its competitors. I know it can be tedious, especially at the beginning of a new project, having to enable all these object-modifiers etc. to make things work. But I see the advantages and have to fight my lazyness and prove myself discipline.

If you have no problem with a few unnecessary kilobytes, or using a tool like uncss, it would be an option to create a seetings file with all `$inuit-enable...` variables and set them all to `true` to enable everything.

**Comment by nenadjelovac** [comment]
@csshugs totally with you on this. 

> But I see the advantages and have to fight my lazyness and prove myself **discipline**.

This is really the point. The way I do it is that I have a boilerplate "starter-kit" for all my projects where I have `_settings.inuit.scss`. In that file I have everything I use and can easily turn off/on anything. Something like:

> it would be an option to create a seetings file with all $inuit-enable... variables and set them all to true to enable everything.

**Comment by csshugs** [comment]
@nenadjelovac :+1: 

> I have a boilerplate "starter-kit" for all my projects

That's it. I think we have to embrace the fact that we always have to build our own kind of boilerplate for our own projects were we adjust these things to our needs and don't expect inuit to fulfill our expectations to that subjective extend.

**Comment by florianbouvot** [comment]
@csshugs @nenadjelovac thanks for your feedback, I think you are right. 

I don't want to ask any change on inuitcss :
- enable option is not a big deal 
- uncss seems risky to me, especially with external plugins like slider, carousel...

But I started looking seriously at Sass alternative like PostCSS...

**Comment by nenadjelovac** [comment]
@csshugs exactly. It's better and easier for developer to adjust to framework than for framework to adjust to whole lot of different usage cases.

@florianbouvot no problem ;)

**Comment by anselmh** [comment]
Thanks for raising the discussion. We’re not going to change anything here at the moment so I’m going to close this issue.
