### ISSUE TITLE
Bower install warnings listed

### ISSUE THREAD

**Issue by iDGS** [inuitcss/CONTRIBUTING#3]
Just for fun (!) I uninstalled all of InuitCSS and then installed all components separately. Good news: all of the given Bower install instructions worked just fine! However, many also resulted in what look to me like a minor complaint or two.  Unfortunately, I don't know quite enough at the moment to offer a solution. However, I can at least offer the list (in what I hope is a useful format--see key at the bottom):

<pre><code>- inuit-bare-list (0.2.1)
- inuit-block-list (0.3.1)
                                √ inuit-box-sizing (0.2.0)
- inuit-box (0.4.0)
- inuit-buttons (0.4.1)
- inuit-clearfix (0.2.0)
                                √ inuit-defaults (0.2.0)
- inuit-flag (0.3.1)
                                √ inuit-functions (0.2.0)
- inuit-headings (0.2.1)
- inuit-images (0.2.0)
- inuit-layout (0.3.1)
+ inuit-lists (0.1.0)
- inuit-media (0.4.0)
                                √ inuit-mixins (0.1.2)
                                √ inuit-normalize (3.0.1)
                                √ inuit-page (0.2.1)
- inuit-paragraphs (0.1.2)
- inuit-reset (0.1.1)
- inuit-responsive-settings (0.1.1)
- inuit-responsive-tools (0.1.1)
- inuit-shared (0.1.3)
- inuit-spacing (0.6.1)
- inuit-tables (0.2.1)
- inuit-tabs (0.2.1)
- inuit-ui-list (0.3.1)
- inuit-widths (0.3.1)

- 1 warning: `is missing "ignore" entry in bower.json`
+ 2 warnings: (above) plus `is missing "main" entry in bower.json`
√ OK - No warnings</code></pre>

**Comment by csswizardry** [comment]
These aren’t anything to worry about; just optional Bower config options that aren’t present. Also, the warnings are inconsistent; none of the `bower.json` files have an `ignore` entry, so none of these should have a tick with them.

Closing this as it’s not actually a problem, but thanks for flagging it :)
