### ISSUE TITLE
Trumps.print module

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/CONTRIBUTING#5]
As per [html5boilerplate](https://github.com/h5bp/html5-boilerplate/blob/master/css/main.css) (or if you know a better one).

**Comment by florianbouvot** [comment]
+1
I use it in my projets but added I added the generic layer :D 
What do you think : generic or trumps ?

**Comment by nenadjelovac** [comment]
There are two reasons why I put it in trumps:
- It just feels like an override to me (so it's trumping things),
- I like it to get compiled at the bottom of css, so I even import it as the last thing in my main scss file :)

I'm not sure if it makes sense or is it just a personal preference. Would like to hear what Harry has to say about it ;)

**Comment by csswizardry** [comment]
Hey!

My only issue with adding a print stylesheet is that we would have to make some design decisions, which is a huge no-no for inuitcss.

Perhaps if all it did is removed backgrounds etc…?

**Comment by nenadjelovac** [comment]
Damn, I forgot about that. Fair point.

But looking at [print section of h5bp](https://github.com/h5bp/html5-boilerplate/blob/master/css/main.css#L205) there are not many design decisions (removing backgrounds and adding border to `blockquote` is what I see from quick scan) that needs discussing. Maybe if it's controlled via variables?

**Comment by graste** [comment]
I'd recommend introducing variables for the decisions. Even backgrounds removal might be something that is not okay for projects. Other than that I'd really like to see a simple print support. :+1:

**Comment by csswizardry** [comment]
I suppose the beauty of the new inuitcss setup is that if people _do_ think the print stylsheet it too opinionated, at least they can just not include it at all—nothing is ever forced upon anyone :)

To that end, perhaps `0.1.0` is just the removal of backgrounds and setting colours to black…?

**Comment by csswizardry** [comment]
https://trello.com/c/7jKliI5W/13-print-module

**Comment by nenadjelovac** [comment]
> I suppose the beauty of the new inuitcss setup is that if people do think the print stylsheet it too opinionated, at least they can just not include it at all—nothing is ever forced upon anyone :)

:+1: 

> To that end, perhaps 0.1.0 is just the removal of backgrounds and setting colours to black…?

Probably just that (as far as design goes). I don't have much experience with css printing, so I've been using h5bp print as sort of a 'normalize' for print.

**Comment by csswizardry** [comment]
How’s this for now? https://github.com/inuitcss/trumps.print

**Comment by nenadjelovac** [comment]
Looks good to me. +1

**Comment by graste** [comment]
:+1:
