### ISSUE TITLE
Add Sass import path to module description  

### ISSUE THREAD

**Issue by christophengelmayer** [inuitcss/CONTRIBUTING#6]
Hi Harry,

I really like the new inuit.css!

While playing around a little bit I noticed that it would be much more convenient to install new modules if you add the default import path to the README.md of each module.
Right now there is only the bower install command.

e.g.:

Install using Bower:

```
$ bower install --save inuit-page
```

Include in your main sass file:

```
@import "bower_components/inuit-page/base.page";
```

**Comment by csswizardry** [comment]
This is a sensible idea… I will look at adding this to the repos :)

**Comment by mhauken** [comment]
+1

**Comment by csshugs** [comment]
@slashadmin 
So that all the READMEs have been updated according to your suggestion, can you close this issue?

By the way: http://sassnotsass.com/ ;-)
