### ISSUE TITLE
inuit-toggle-responsive - object to generate mobile navigation menus

### ISSUE THREAD

**Issue by christophengelmayer** [inuitcss/CONTRIBUTING#9]
I created a small object for inuit. It hides an element and adds a button to toggle its visibility on small viewports. Uses a checkbox and :target selector to toggle (no javascript needed, >=IE9). It could be used to create a responsive navigation menu.

Repo:
https://github.com/slashadmin/inuit-toggle-responsive

The idea to use a checkbox and a :target selector is from the following posts:
http://blog.lavoie.sl/2013/11/responsive-menu-in-pure-css.html
https://coderwall.com/p/sujd_w

Demo:
http://jsfiddle.net/N53dj/

What do you think? Any suggestions?

**Comment by colourgarden** [comment]
This is quite cool but isn't an Inuit-dependent component and not really a common enough pattern to warrant inclusion, in my opinion.

**Comment by nenadjelovac** [comment]
> This is quite cool but isn't an Inuit-dependent component and not really a common enough pattern to warrant inclusion, in my opinion.

I agree.
